name: build

on:
  pull_request:
    paths-ignore:
      - '.idea/**'
      - '.gitignore'
      - '*.md'

  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
    paths-ignore:
      - '.idea/**'
      - '.gitignore'
      - '*.md'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 19

      - run: ./gradlew build
