name: build

on:
  pull_request:
    paths-ignore:
      - '.idea/**'
      - '.gitignore'
      - '*.md'

  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'
    paths-ignore:
      - '.idea/**'
      - '.gitignore'
      - '*.md'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-konan-
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 19

      - uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          arguments: build

# Test 2
